app:
  name: "web_app"
  mode: "dev"
  port: 8086
  version: "v1.0.0"
  start_time: "2023-10-01"
  machine_id: 1

auth:
  jwt_expire: 8760
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: mysql8034
  port: 3306
  user: "root"
  password : "123"
  dbname: "goapp"
  max_open_conns: 20
  max_idle_conns: 10
redis:
  host: redis723
  port: 6379
  password: ""
  db: 0
  pool_size: 20
